# Generated by Django 4.2.3 on 2024-08-30 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_doctorsprofile_user_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('GP', 'General Practitioner'), ('CARD', 'Cardiologist'), ('DERM', 'Dermatologist'), ('ORTH', 'Orthopedic'), ('NEUR', 'Neurologist'), ('DENT', 'Dental')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorsprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
